---
abstract: 'Gets information from yahoo weather.'
author:
  - 'Hernan Lopes (hernanlopes@gmail.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Weather-Yahoo
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: 0.44
  WWW::Mechanize: 0
  XML::XPath: 0
version: 0.07
